language: node_js

node_js:
  - "4"
  - "5"

install: npm install

notifications:
  email:
    recipients:
      - kidd.fan@104.com.tw
    on_success: always
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text